config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  
  root 'tasks#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  private
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "Should be less than 5MB.")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tasks
         
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :usertype])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    if current_user != @task.user
      if @task.status == true
        @task.taken_by == current_user.id
      end
    end
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    
    respond_to do |format|
      
      if @task.update(task_params)
        
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :picture, :user_id, :status, :done, :taken_by, :location)
    end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  
  before_filter :configure_permitted_parameters
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
    devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PlaneteersApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PlaneteersApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"> </li>
              <li class="col-md-3 logout">
                <%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %>
              </li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to t(".sign_up", :default => "Sign up"), new_registration_path(resource_name) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>


    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div>

      
      <footer>
        <p>&copy; Company 2016</p>
      </footer>
      

    </div>

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { multipart: true, :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <% if current_user == @task.user %>
  
    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :location, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :location, :class => 'form-control', placeholder: "Add link from google maps" %>
      </div>
      <%=f.error_span(:name) %>
    </div>
    <div class="form-group">
      <%= f.label :picture, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', :class => 'form-control' %>
      </div>
      <%=f.error_span(:picture) %>
    </div>
  
  <% else %>
  
    <% if @task.status == false %>
    
      <div class="form-group">
        <div class="row">
          <label class="col-lg-4 col-lg-offset-2">Responsible for this task will be <%= current_user.full_name %> </label>
        </div>
        <div class="col-lg-4 col-lg-offset-2 hidden-lg hidden-md hidden-sm hidden-xs">
          <%= f.select :taken_by, [current_user.id], :class => 'form-control' %>
        </div>
      </div>
  
      <div class="form-group">
        <div class="row">
          <label class="col-lg-4 col-lg-offset-2">I'm gonna take this task</label>
        </div>
        <div class="col-lg-4 col-lg-offset-2">
          <%= f.select :status, ['false', 'true'], :class => 'form-control' %>
        </div>
        <%=f.error_span(:status) %>
      </div>
    
    <% else %>
  
    
      <div class="form-group">
        <div class="row">
          <label class="col-lg-4 col-lg-offset-2">The task is done</label>
        </div>
        <div class="col-lg-4 col-lg-offset-2">
          <%= f.select :done, ['false', 'true'], :class => 'form-control' %>
        </div>
        <%=f.error_span(:done) %>
      </div>
      
    <% end %>
  <% end %>
  
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('Maximum file size is 5MB.');
    }
  });
</script>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:done) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= link_to task.name, task_path(task) %></td>
        <td><%= link_to 'Open in Google Maps', task.location, :target => "_blank" %></td>
        <td><%= task.status %></td>
        <td><%= task.done %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to 'Show', task_path(task), :class => 'btn btn-default btn-xs' %>
          
          <% if task.user == current_user %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-default btn-xs' %>
          <% else %>
            
            <% if task.status == false %>
              <% if current_user.usertype == "planeteer" %>
                <%= link_to 'Take', edit_task_path(task), :class => 'btn btn-default btn-xs' %>
              <% end %>
            <% else %>
              <% if task.done == false %>
                <% if task.taken_by == current_user.id %>
                  <% if current_user.usertype == "planeteer" %>
                    <%= link_to 'End task', edit_task_path(task), :class => 'btn btn-default btn-xs' %>
                  <% end %>
                <% else %>
                  <p><small>In Progress</small></p>
                <% end %>
              <% else %>
                <p><small>Finished</small></p>
              <% end %>
            <% end %>
          
          <% end %>
          <% if task.user == current_user %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        task_path(task),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.usertype == "contributor" %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>

<%= form_for @task, :html => { multipart: true, :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :location, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :location, :class => 'form-control', placeholder: "Add link from google maps" %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :picture, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', :class => 'form-control' %>
    </div>
    <%=f.error_span(:picture) %>
  </div>
  

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $('#image_picture').bind('change', function(){
    var size_in_megabytes = this.files[0].size/1024/1024;
    if(size_in_megabytes > 5){
      alert('Maximum file size is 5MB.');
    }
  });
</script>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd><br>
  <dt><strong><%= model_class.human_attribute_name(:picture) %>:</strong></dt>
  <dd><%= image_tag(@task.picture.url, size:"300x300") if @task.picture? %></dd>
  
  <br>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= link_to 'Open in Google Maps', @task.location, :target => "_blank" %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @task.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @task.done %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn btn-default'  %>
              
<% if current_user == @task.user %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn btn-default' %>
<% else %>
  <% if @task.status == false %>
    <% if current_user.usertype == "planeteer" %>
      <%= link_to 'Take', edit_task_path(@task), :class => 'btn btn-default' %>
    <% end %>
  <% else %>
    <% if @task.done == false %>
      <% if current_user.id == @task.taken_by %>
        <% if current_user.usertype == "planeteer" %>
          <%= link_to 'End task', edit_task_path(@task), :class => 'btn btn-default' %>
        <% end %>
      <% else %>
        <p><small>In progress</small></p>
      <% end %>  
    <% else %>
      <p><small>Finished</small></p>
    <% end %>
  <% end %>
<% end %>

<% if current_user == @task.user %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome <%= current_user.full_name %></h1>